//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duikboot.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dag()
        {
            this.Dag_Meerijder = new HashSet<Dag_Meerijder>();
        }
    
        public int ID { get; set; }
        public string date { get; set; }
        public Nullable<int> available_spots { get; set; }
        public string name { get; set; }
        public Nullable<decimal> price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dag_Meerijder> Dag_Meerijder { get; set; }
    }
}
