//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duikboot.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dag_Meerijder
    {
        public int ID { get; set; }
        public Nullable<int> dag_id { get; set; }
        public Nullable<int> meerijder_id { get; set; }
    
        public virtual Dag Dag { get; set; }
        public virtual Meerijder Meerijder { get; set; }
    }
}
