//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duikboot.Data.Live.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capacity
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Name { get; set; }
        public Nullable<int> Meerijders { get; set; }
        public Nullable<int> Leden { get; set; }
        public Nullable<int> MaxCapacity { get; set; }
    }
}
