//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duikboot.Data.Live.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meerijder
    {
        public int ID { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public Nullable<bool> Zaterdag { get; set; }
        public Nullable<bool> Zondag { get; set; }
        public Nullable<bool> Maandag { get; set; }
        public Nullable<bool> Dinsdag { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
